#!/usr/bin/env python4
"""
Test Recipe Recommendation Engine Implementation
Tests the AI-powered recipe recommendation system functionality
"""

import sys
import os
import sqlite3
import json
from datetime import datetime

# Add family_manager to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'family_manager'))

def test_database_tables():
    """Test that recipe recommendation database tables are created"""
    print("🧪 Testing database table creation...")
    
    try:
        from api import init_recipe_tables, get_db
        
        # Initialize tables
        init_recipe_tables()
        
        # Verify tables exist
        conn = get_db()
        cursor = conn.cursor()
        
        tables_to_check = [
            'favorite_recipes',
            'recipe_history', 
            'user_preferences',
            'recipe_suggestions'
        ]
        
        for table in tables_to_check:
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table,))
            result = cursor.fetchone()
            if result:
                print(f"✅ Table '{table}' exists")
            else:
                print(f"❌ Table '{table}' missing")
        
        conn.close()
        return True
        
    except Exception as e:
        print(f"❌ Database test failed: {e}")
        return False

def test_recipe_data_operations():
    """Test basic recipe data operations"""
    print("\n🧪 Testing recipe data operations...")
    
    try:
        conn = sqlite3.connect('family_manager/family_manager.db')
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        # Test adding a sample favorite recipe
        test_recipe = {
            'recipe_name': 'Test AI Recipe',
            'ingredients': 'Tomatoes, Pasta, Cheese, Herbs',
            'instructions': 'Cook pasta, add tomatoes and cheese, season with herbs',
            'cuisine_type': 'Italian',
            'cooking_time': 25,
            'difficulty': 'Easy',
            'rating': 5,
            'notes': 'Generated by recipe recommendation test',
            'created_date': datetime.now().isoformat()
        }
        
        cursor.execute("""
            INSERT OR REPLACE INTO favorite_recipes 
            (recipe_name, ingredients, instructions, cuisine_type, cooking_time, 
             difficulty, rating, notes, created_date)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            test_recipe['recipe_name'],
            test_recipe['ingredients'],
            test_recipe['instructions'],
            test_recipe['cuisine_type'],
            test_recipe['cooking_time'],
            test_recipe['difficulty'],
            test_recipe['rating'],
            test_recipe['notes'],
            test_recipe['created_date']
        ))
        
        conn.commit()
        print("✅ Sample recipe added to favorites")
        
        # Test retrieving favorites
        cursor.execute("SELECT recipe_name FROM favorite_recipes WHERE recipe_name = ?", 
                      (test_recipe['recipe_name'],))
        result = cursor.fetchone()
        
        if result:
            print("✅ Recipe retrieved from favorites")
        else:
            print("❌ Recipe not found in favorites")
        
        # Test adding user preferences
        cursor.execute("""
            INSERT OR REPLACE INTO user_preferences (preference_type, preference_value)
            VALUES (?, ?)
        """, ('dietary_restriction', 'vegetarian'))
        
        cursor.execute("""
            INSERT OR REPLACE INTO user_preferences (preference_type, preference_value) 
            VALUES (?, ?)
        """, ('cuisine_preference', 'Italian'))
        
        conn.commit()
        print("✅ User preferences added")
        
        conn.close()
        return True
        
    except Exception as e:
        print(f"❌ Recipe data operations test failed: {e}")
        return False

def test_ai_recipe_functions():
    """Test AI recipe generation functions"""
    print("\n🧪 Testing AI recipe functions...")
    
    try:
        # Test fallback recipe generation (without actual AI)
        from api import parse_ai_recipe_response
        
        # Test text parsing fallback
        sample_response = """
        Recipe Name: Test Pasta Recipe
        Ingredients: Pasta, Tomatoes, Cheese
        Instructions: Cook pasta, add sauce, serve hot
        Time: 20 minutes
        """
        
        parsed_recipes = parse_ai_recipe_response(sample_response)
        
        if parsed_recipes and len(parsed_recipes) > 0:
            print("✅ AI recipe text parsing works")
            print(f"   Sample recipe: {parsed_recipes[0].get('name', 'N/A')}")
        else:
            print("❌ AI recipe text parsing failed")
        
        return True
        
    except Exception as e:
        print(f"❌ AI recipe functions test failed: {e}")
        return False

def test_recipe_recommendation_api():
    """Test recipe recommendation API endpoints (basic validation)"""
    print("\n🧪 Testing recipe recommendation API structure...")
    
    try:
        from api import app
        
        # Get all routes
        routes = []
        for rule in app.url_map.iter_rules():
            routes.append(rule.rule)
        
        expected_recipe_routes = [
            '/api/recipes/recommendations',
            '/api/recipes/by-ingredients', 
            '/api/recipes/favorites',
            '/api/recipes/nutrition-analysis'
        ]
        
        for route in expected_recipe_routes:
            if route in routes:
                print(f"✅ Route '{route}' registered") 
            else:
                print(f"❌ Route '{route}' missing")
        
        return True
        
    except Exception as e:
        print(f"❌ API route test failed: {e}")
        return False

def test_sample_inventory_data():
    """Add sample inventory data for testing recommendations"""
    print("\n🧪 Adding sample inventory data...")
    
    try:
        conn = sqlite3.connect('family_manager/family_manager.db')
        cursor = conn.cursor()
        
        # Add sample ingredients
        sample_ingredients = [
            ('Tomatoes', 'Vegetables', 5, 'pieces', '2026-02-15'),
            ('Pasta', 'Grains', 2, 'boxes', '2026-12-31'),
            ('Chicken Breast', 'Protein', 3, 'lbs', '2026-02-05'),
            ('Onions', 'Vegetables', 4, 'pieces', '2026-02-20'),
            ('Garlic', 'Spices', 1, 'bulb', '2026-03-01'),
            ('Olive Oil', 'Condiments', 1, 'bottle', '2026-08-15'),
            ('Rice', 'Grains', 1, 'bag', '2026-10-31'),
            ('Bell Peppers', 'Vegetables', 3, 'pieces', '2026-02-10'),
        ]
        
        for ingredient in sample_ingredients:
            cursor.execute("""
                INSERT OR REPLACE INTO inventory 
                (name, category, qty, unit, exp_date)
                VALUES (?, ?, ?, ?, ?)
            """, ingredient)
        
        conn.commit()
        print(f"✅ {len(sample_ingredients)} sample ingredients added to inventory")
        
        # Verify ingredients
        cursor.execute("SELECT COUNT(*) FROM inventory WHERE qty > 0")
        count = cursor.fetchone()[0]
        print(f"✅ Total available ingredients: {count}")
        
        conn.close()
        return True
        
    except Exception as e:
        print(f"❌ Sample inventory data test failed: {e}")
        return False

def main():
    """Run all recipe recommendation tests"""
    print("🚀 RECIPE RECOMMENDATION ENGINE TESTS")
    print("=" * 50)
    
    tests = [
        test_database_tables,
        test_sample_inventory_data,
        test_recipe_data_operations,
        test_ai_recipe_functions,
        test_recipe_recommendation_api
    ]
    
    passed = 0
    total = len(tests)
    
    for test in tests:
        try:
            if test():
                passed += 1
        except Exception as e:
            print(f"❌ Test {test.__name__} crashed: {e}")
    
    print("\n" + "=" * 50)
    print(f"🎯 TEST RESULTS: {passed}/{total} tests passed")
    
    if passed == total:
        print("✅ All recipe recommendation tests PASSED!")
        print("\n🎉 Recipe Recommendation Engine is working correctly!")
        print("\nKey Features Tested:")
        print("  ✅ Database tables for recipes, favorites, preferences")
        print("  ✅ Recipe data operations (CRUD)")
        print("  ✅ AI recipe function structure")
        print("  ✅ API endpoint registration")
        print("  ✅ Sample inventory data for recommendations")
        return True
    else:
        print("❌ Some tests failed. Check implementation.")
        return False

if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"FATAL ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)